import express from "express";
import createRoomController from "../controllers/createRoomController";
import joinRoomController from "../controllers/joinRoomController";
import leaveRoomController from "../controllers/leaveRoomController";
import codeChangeController from "../controllers/codeChangeController";
import usersInRoom from "../controllers/usersInRoom";
import languageChangeController from "../controllers/languageChangeController";
import getCodeController from "../controllers/getCodeController";
import authMiddleware from "../middleware/authMiddleware";
const roomRoute=express.Router();
roomRoute.post("/create",authMiddleware,createRoomController);
roomRoute.post("/join",authMiddleware,joinRoomController);
roomRoute.post("/leave",authMiddleware,leaveRoomController);
roomRoute.post("/code-change",authMiddleware,codeChangeController);
roomRoute.post("/users",authMiddleware,usersInRoom);
roomRoute.post("/language-change",authMiddleware,languageChangeController);
roomRoute.post("/get-code",authMiddleware,getCodeController);
export default roomRoute;