import express from "express";
import createRoomController from "../controllers/createRoomController";
import joinRoomController from "../controllers/joinRoomController";
import leaveRoomController from "../controllers/leaveRoomController";
import authMiddleware from "../middleware/authMiddleware";
const roomRoute=express.Router();
roomRoute.post("/create",authMiddleware,createRoomController);
roomRoute.post("/join",authMiddleware,joinRoomController);
roomRoute.post("/leave",authMiddleware,leaveRoomController);
export default roomRoute;